In [5]:
import numpy as np
from matplotlib import pyplot as plt
from pyDOE import lhs

In [29]:
lowB = [0,0,0]
upperB = [1,1,0.5]

numX = 16
numY = 16
numT = 16

x = np.linspace(lowB[0], upperB[0], numX)
y = np.linspace(lowB[1], upperB[1], numY)
t = np.linspace(lowB[2], upperB[2], numY)
X, Y, T = np.meshgrid(x, y, t)
X = X.flatten()
Y = Y.flatten()
T = T.flatten()
ptsAll = np.transpose([X, Y, T])

In [32]:
ptsAll

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.03333333],
       [0.        , 0.        , 0.06666667],
       ...,
       [1.        , 1.        , 0.43333333],
       [1.        , 1.        , 0.46666667],
       [1.        , 1.        , 0.5       ]])

In [44]:
ptsBD_x0y = np.array(list((map(lambda x: np.extract(ptsAll[:,0] == 0.0, ptsAll[:,x]), [0,1,2])))).transpose()
ptsBD_xy1 = np.array(list((map(lambda x: np.extract(ptsAll[:,1] == 1.0, ptsAll[:,x]), [0,1,2])))).transpose()
ptsBD_x1y = np.array(list((map(lambda x: np.extract(ptsAll[:,0] == 1.0, ptsAll[:,x]), [0,1,2])))).transpose()
ptsBD_xy0 = np.array(list((map(lambda x: np.extract(ptsAll[:,1] == 0.0, ptsAll[:,x]), [0,1,2])))).transpose()

In [47]:
ptsBD = [ptsBD_x0y, ptsBD_xy1, ptsBD_x1y, ptsBD_xy0]

In [37]:
ptsCL =np.array(list(map(lambda x: np.extract(np.bitwise_and(ptsAll[:, x] <= upperB[x], ptsAll[:, x] >= lowB[x]), ptsAll[:, x]), [0, 1, 2]))).transpose()

In [48]:
ptsBD[0]

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.03333333],
       [0.        , 0.        , 0.06666667],
       [0.        , 0.        , 0.1       ],
       [0.        , 0.        , 0.13333333],
       [0.        , 0.        , 0.16666667],
       [0.        , 0.        , 0.2       ],
       [0.        , 0.        , 0.23333333],
       [0.        , 0.        , 0.26666667],
       [0.        , 0.        , 0.3       ],
       [0.        , 0.        , 0.33333333],
       [0.        , 0.        , 0.36666667],
       [0.        , 0.        , 0.4       ],
       [0.        , 0.        , 0.43333333],
       [0.        , 0.        , 0.46666667],
       [0.        , 0.        , 0.5       ],
       [0.        , 0.06666667, 0.        ],
       [0.        , 0.06666667, 0.03333333],
       [0.        , 0.06666667, 0.06666667],
       [0.        , 0.06666667, 0.1       ],
       [0.        , 0.06666667, 0.13333333],
       [0.        , 0.06666667, 0.16666667],
       [0.

In [52]:
from torch.autograd import Variable
import torch

def variablize(pts, reqGrad=None):
    if reqGrad is None:
        reqGrad = [True, True, True]
    colX = Variable(torch.from_numpy(pts[:, 0].astype(np.float32)), requires_grad=reqGrad[0]).cuda()
    colY = Variable(torch.from_numpy(pts[:, 1].astype(np.float32)), requires_grad=reqGrad[1]).cuda()
    colT = Variable(torch.from_numpy(pts[:, 2].astype(np.float32)), requires_grad=reqGrad[2]).cuda()
    return colX, colY, colT

In [53]:
 colX, colY, colT = variablize(ptsBD[0], [True, True, False])

In [54]:
colX

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 